### ISSUE TITLE
More standardization enforcement

### ISSUE THREAD

**Issue by lw-ryanhirsch** [stevencrader/transcriptator#1]
Right now I see prettier is added, but would also be a good idea to get eslint going too. Would help with consistency and limit any additional ambiguity around styling and preferences.

**Comment by stevencrader** [comment]
Good idea. I get it added.

**Comment by RyanHirsch** [comment]
> I get it added.

I'm not trying to hoist work on to you, I can do it if you let me know what rules you want disabled on #2 
You can then add whatever additional rules once its merged to `dev`.

**Comment by stevencrader** [comment]
Resolved with #2 merge
