### ISSUE TITLE
Add support for custom timestamp formatter

### ISSUE THREAD

**Issue by stevencrader** [stevencrader/transcriptator#11]
Some users need the start and end time in a format other than the default. 

Add support for specifying a formatter function. The function shall accept 1 argument (number, seconds) and returns a formatted string.

**Comment by mitchdowney** [comment]
I started looking into this, but ran into a problem and I'm not sure of a good way to handle it...there is an existing `formatTimestamp` function, and I'd like to conditionally tell transcriptator to use a custom format function if provided...but it seems like to do that we'd either need to 1) pass in the custom formatter function as a parameter into `convertFile`, and then all the way down into `formatTimestamp`, or 2) instantiate some kind of transcriptator singleton that we can assign a custom formatter to, then use it within `formatTimestamp` if available.

1 seems like a bad option, with functions getting passed down as parameters in multiple places, but 2 seems like a bigger change than I was hoping for something like this.

Any ideas for how to proceed?

**Comment by stevencrader** [comment]
I agree that passing the function through the multiple levels doesn't seem like the way to go. 

If you have an idea for how to reformat to support a singleton in `formatTimestamp`, go for it.

**Comment by stevencrader** [comment]
Hey @mitchdowney, not sure if you looked at this any further but I've added a possible solution. See https://github.com/stevencrader/transcriptator/pull/12.

Does that change work for you?

If you have a different proposal, I'm happy to use it instead.
